---
- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: yes
    state: present

- name: Import Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker CE
  apt:
    name: docker-ce={{ docker_version }}
    update_cache: yes
    state: present

- name: Configure Docker create /etc/docker folder
  file:
    path: /etc/docker
    state: directory
    recurse: yes
    mode: 0700
    owner: root
    group: root

- name: Configure Docker for user native systemd cgroupdriver
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  when: 
    - docker_cgroup_driver == "systemd"

- name: Remove node key
  file:
    path: /etc/docker/key.json
    state: absent

- name: debug
  debug:
    var: docker_end_status

- name: Docker service enabled and in status "{{ docker_end_status }}"
  systemd:
    state: "{{ docker_end_status }}"
    daemon_reload: yes
    name: docker
