---
dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
platforms:
  - name: instance-1
    image: "ubuntu1804-master-3"
    flavor: o1.highcpu-spot.x2
provisioner:
  name: ansible
  options:
    diff: True
    v: True
  playbooks:
    create: create.yml
    prepare: prepare.yml
    destroy: destroy.yml
scenario:
  name: default
verifier:
  name: goss
